<div class="container pagina-estrutura">
<nav class="study-nav" aria-label="Trilha de estudos"><a href="../index.php">← Início</a><a href="fila-fifo.php">Fila FIFO</a><a href="fila-prioridade.php">Prioridades</a><a href="pilha.php">Pilha</a><a href="../quiz.php">Praticar no quiz ↗</a></nav>
<header class="hero-estrutura"><span class="eyebrow">Laboratório de estruturas</span><h1><?=htmlspecialchars($aula['titulo'])?></h1><p><?=htmlspecialchars($aula['regra'])?></p></header>
<section class="teoria-box"><h2>Entenda a lógica</h2><p><?=htmlspecialchars($aula['texto'])?></p><h3>Onde usar</h3><p><?=htmlspecialchars($aula['uso'])?></p><div class="destaque"><strong>Custo das operações</strong><br><?=htmlspecialchars($aula['custo'])?></div><p>Remover ou consultar uma estrutura vazia lança uma exceção no exemplo em C#. No simulador, você recebe uma mensagem sem alterar a estrutura.</p></section>
<section class="visualizador" data-estrutura="<?=$slug?>"><span class="badge">Experimente</span><h2>Veja os nós em ação</h2><p>Adicione valores e acompanhe como as referências mudam.</p><form id="vizForm"><div class="viz-controles"><input id="valorEstrutura" aria-label="Valor do novo nó" placeholder="Valor do nó" maxlength="12" required><?php if($slug==='fila_prioridade'):?><input id="prioridadeEstrutura" type="number" step="1" min="-999" max="999" value="1" aria-label="Prioridade (maior número sai primeiro)"><?php endif;?><button class="btn-primario">Adicionar</button><button class="btn-secundario" id="vizRemover" type="button">Remover</button><button class="btn-secundario" id="vizLimpar" type="button">Limpar</button></div></form><div id="vizEstrutura" class="nos-container"></div><p id="vizMensagem" class="dica" role="status" aria-live="polite">A estrutura está vazia. Adicione seu primeiro nó.</p></section>
<section><h2>Uma operação por vez</h2><div class="media-grid"><figure><img src="../assets/media/<?=$slug?>.gif" alt="Animação das inserções e remoções de <?=htmlspecialchars($aula['titulo'])?>" loading="lazy"><figcaption>GIF: acompanhe a ordem dos nós e o elemento removido.</figcaption></figure><figure><video controls preload="metadata" aria-label="Vídeo demonstrativo de <?=htmlspecialchars($aula['titulo'])?>"><source src="../assets/media/<?=$slug?>.mp4" type="video/mp4"><track default kind="captions" src="../assets/media/<?=$slug?>.vtt" srclang="pt-BR" label="Português"></video><figcaption>Vídeo demonstrativo local, com legendas e controles de reprodução.</figcaption></figure></div></section>
<section class="codigo-card bloco-codigo"><div class="pagina-titulo"><h2>Implementação completa em C#</h2><button type="button" class="btn-secundario btn-copiar">Copiar código</button></div><p class="dica">Exemplo independente para .NET 8. Inclui nós, operações, tratamento de estrutura vazia e Main.</p><pre><code class="language-csharp"><?=htmlspecialchars($aula['codigo'])?></code></pre><a href="../assets/examples/<?=$slug?>.cs" download>Baixar exemplo .cs ↓</a></section>
<section class="teoria-box" style="margin-top:24px"><h2>Teste seu raciocínio</h2><p><?=htmlspecialchars($aula['exercicio'])?></p><details><summary>Conferir resposta</summary><p><?=htmlspecialchars($aula['resposta'])?></p></details></section>
<?php foreach($aula['extras'] as $c):?><article class="bloco-conteudo"><span class="badge"><?=htmlspecialchars($c['tipo'])?></span><h3><?=htmlspecialchars($c['titulo'])?></h3><?php if($c['tipo']==='codigo'):?><pre><code><?=htmlspecialchars($c['conteudo'])?></code></pre><?php else:?><div><?=nl2br(strip_tags($c['conteudo'],'<p><b><strong><em><ul><ol><li><br><code>'))?></div><?php endif;?></article><?php endforeach;?>
</div><script src="../assets/js/estruturas.js"></script>
