<div class="container game-page quiz-experience">
<nav class="game-nav" aria-label="Área de jogos"><a href="area-usuario.php">← Minha área</a><div><a href="quiz.php?preparar=1" aria-current="page">Quiz</a><a href="avatar.php">Personagem</a><a href="loja.php">Loja</a></div><span class="coin-pill">◈ <?=(int)$u['moedas']?> <span>moedas</span></span></nav>
<?php mostrarFlash();$resultado=$_SESSION['quiz_resultado']??null;?>
<?php if($lobby):?>
<header class="game-heading"><span class="eyebrow">Laboratório de conhecimento</span><h1>Seu conhecimento.<br><span>Sua próxima conquista.</span></h1><p>Conecte a teoria à prática, entenda cada resposta e dê um novo passo na sua evolução.</p></header>
<div class="quiz-lobby-grid"><section class="challenge-card"><div class="challenge-symbol" aria-hidden="true">{ ? }</div><span class="badge">Desafio completo</span><h2>Pronto para testar sua lógica?</h2><p>Um percurso por TAD, listas, filas e pilhas. Sem cronômetro: pense, responda e aprenda no seu ritmo.</p><div class="challenge-facts"><div><strong>10</strong><span>questões por rodada</span></div><div><strong>6</strong><span>temas de estudo</span></div><div><strong>C#</strong><span>teoria + código</span></div></div><a class="btn-primario challenge-start" href="quiz.php?novo=1"><?=isset($_SESSION['quiz_perguntas'])?'Recomeçar desafio':'Começar desafio'?> →</a><?php if(isset($_SESSION['quiz_perguntas'])):?><a class="resume-link" href="quiz.php">Continuar partida em andamento →</a><p class="dica">Recomeçar descarta as respostas da partida em andamento.</p><?php endif;?><p class="dica">Recompensas ao concluir: 20 moedas + 10 por acerto e 10 XP por acerto.</p></section>
<aside class="quiz-companion"><div class="companion-character"><?php require __DIR__.'/character.php';?></div><span class="badge">Nível <?=(int)$u['nivel']?></span><h2>Seu parceiro de estudos</h2><p>As habilidades equipadas entram com você no desafio.</p><?php require __DIR__.'/powers.php';?><a href="avatar.php" class="btn-secundario">Preparar personagem ↗</a></aside></div>
<section class="quiz-history"><div class="catalog-heading"><h2>Suas últimas partidas</h2><span>Até 5 desafios recentes</span></div><?php if(!$history):?><div class="history-empty"><span>↗</span><div><h3>Toda jornada começa com uma tentativa.</h3><p>Seu primeiro resultado aparecerá aqui. Vamos começar?</p></div></div><?php else:?><div class="history-list"><?php foreach($history as $h):?><div class="history-row"><span class="history-score"><?=$h['acertos']?>/<?=$h['total']?></span><div><strong><?=round(100*$h['acertos']/max(1,$h['total']))?>% de aproveitamento</strong><small><?=date('d/m/Y · H:i',strtotime($h['realizado_em']))?></small></div><span>+<?=$h['moedas_ganhas']?> ◈</span><span>+<?=$h['xp_ganho']?> XP</span></div><?php endforeach;?></div><?php endif;?></section>
<?php elseif($resultado):$percent=round(100*$resultado['acertos']/max(1,$resultado['total']));?>
<section class="quiz-finish"><div class="finish-medal" aria-hidden="true">✦</div><span class="eyebrow">Desafio concluído</span><h1><?=$percent>=70?'Você está construindo conhecimento.':'Cada tentativa ensina algo novo.'?></h1><p>Você acertou <strong><?=$resultado['acertos']?> de <?=$resultado['total']?></strong> questões. Revise suas respostas e siga evoluindo.</p><div class="reward-grid"><div><span>◈</span><strong>+<?=$resultado['coins']?></strong><small>moedas recebidas</small></div><div><span>✧</span><strong>+<?=$resultado['xp']?></strong><small>XP conquistado</small></div><div><span>↗</span><strong><?=$percent?>%</strong><small>aproveitamento</small></div></div><div class="finish-actions"><a class="btn-primario" href="quiz.php?novo=1">Jogar novamente →</a><a class="btn-secundario" href="loja.php">Usar minhas moedas</a><a class="text-link" href="quiz.php?preparar=1">Ver histórico</a></div></section>
<section class="answer-review"><div class="catalog-heading"><div><h2>Aprenda com cada resposta</h2><p>Abra uma questão para entender o raciocínio.</p></div><label class="filter-check"><input type="checkbox" data-errors-only> Só as que errei</label></div>
<?php foreach($resultado['respostas'] as $n=>$r):$right=$r['resposta']===$r['correta'];?><details class="review-item <?=$right?'review-right':'review-wrong'?>" data-review data-correct="<?=$right?'true':'false'?>"><summary><span class="review-marker"><?=$right?'✓':'↗'?></span><span><small>QUESTÃO <?=$n+1?> · <?=htmlspecialchars(Game::THEMES[$r['estrutura']??'geral']??'Estruturas')?></small><?=Game::question($r['pergunta'])?></span><span class="review-outcome"><?=$right?'Acertou':'Revisar'?></span></summary><div class="review-body"><p><strong>Sua resposta: <?=$r['resposta']?>.</strong> <?=htmlspecialchars($r['alternativas'][$r['resposta']]??'')?></p><?php if(!$right):?><p class="correct-answer"><strong>Resposta correta: <?=$r['correta']?>.</strong> <?=htmlspecialchars($r['alternativas'][$r['correta']]??'')?></p><?php endif;?><div class="explanation"><strong>Por que essa é a resposta?</strong><p><?=htmlspecialchars($r['explicacao']??'')?></p></div></div></details><?php endforeach;?><p class="history-empty" data-no-errors hidden>Você acertou todas as questões. Excelente trabalho!</p></section>
<?php elseif(empty($_SESSION['quiz_perguntas'])):?><div class="history-empty"><h1>Nenhuma questão disponível.</h1><a href="quiz.php?preparar=1">Voltar à preparação</a></div>
<?php else:$pos=$_SESSION['quiz_pos'];$p=$_SESSION['quiz_perguntas'][$pos];$total=count($_SESSION['quiz_perguntas']);$eliminada=$_SESSION['quiz_eliminada'][$pos]??null;$feedback=$_SESSION['quiz_feedback']??null;?>
<div class="quiz-session-heading"><div><span class="eyebrow">Desafio de estruturas</span><h1><?= $feedback?'Vamos entender a resposta.':'Uma ideia de cada vez.'?></h1></div><span class="session-position">Questão <?=$feedback?$pos:min($pos+1,$total)?> de <?=$total?></span></div>
<div class="question-layout"><section class="question-main"><div class="question-progress"><div class="question-steps" aria-label="<?=$pos?> de <?=$total?> questões respondidas"><?php for($n=0;$n<$total;$n++):$r=$_SESSION['quiz_respostas'][$n]??null;?><span class="<?=$r?($r['resposta']===$r['correta']?'step-right':'step-wrong'):($n===$pos?'step-current':'')?>" aria-label="Questão <?=$n+1?>: <?=$r?($r['resposta']===$r['correta']?'correta':'incorreta'):($n===$pos?'atual':'pendente')?>"><?=$r?($r['resposta']===$r['correta']?'✓':'·'):$n+1?></span><?php endfor;?></div><progress max="<?=$total?>" value="<?=$pos?>" aria-label="Progresso do quiz"></progress></div>
<?php if($feedback):?><div class="question-card feedback-card <?=$feedback['certa']?'feedback-right':'feedback-wrong'?>"><span class="feedback-icon"><?=$feedback['certa']?'✓':'↗'?></span><span class="eyebrow"><?=$feedback['certa']?'Resposta correta':'Uma oportunidade de aprender'?></span><h2><?=Game::question($feedback['pergunta']??'Confira o raciocínio')?></h2><div class="correct-answer"><small>ALTERNATIVA CORRETA</small><strong><?=$feedback['correta']?> · <?=htmlspecialchars($feedback['alternativas'][$feedback['correta']]??'')?></strong></div><?php if(!$feedback['certa']):?><p class="dica">Você marcou <?=$feedback['resposta']??'—'?>. <?=htmlspecialchars($feedback['alternativas'][$feedback['resposta']??'']??'')?></p><?php endif;?><div class="explanation"><strong>Entenda o raciocínio</strong><p><?=htmlspecialchars($feedback['texto']??'')?></p></div><form method="post"><input type="hidden" name="nonce" value="<?=$_SESSION['quiz_nonce']?>"><input type="hidden" name="pos" value="<?=$pos?>"><button class="btn-primario" name="acao" value="continuar">Próxima questão →</button></form></div>
<?php else:?><div class="question-card"><div class="question-label"><span class="badge"><?=htmlspecialchars(Game::THEMES[$p['estrutura']]??'Fundamentos')?></span><span>Escolha uma alternativa</span></div><h2><?=Game::question($p['pergunta'])?></h2>
<form method="post" data-answer-form><input type="hidden" name="nonce" value="<?=$_SESSION['quiz_nonce']?>"><input type="hidden" name="pos" value="<?=$pos?>"><fieldset class="answer-options"><legend class="sr-only">Alternativas da questão</legend><?php foreach(['A'=>'alternativa_a','B'=>'alternativa_b','C'=>'alternativa_c','D'=>'alternativa_d'] as $l=>$c):?><label class="answer-option <?=$eliminada===$l?'answer-eliminated':''?>"><input type="radio" name="resposta" value="<?=$l?>" <?=$eliminada===$l?'disabled':'required'?>><span class="option-letter"><?=$l?></span><span><?= $eliminada===$l?'Alternativa eliminada pelo Boné do Código':Game::question($p[$c])?></span><span class="option-check" aria-hidden="true">✓</span></label><?php endforeach;?></fieldset><div class="answer-submit"><span class="dica" data-answer-status>Selecione sua resposta para continuar.</span><button class="btn-primario" data-answer-submit>Confirmar resposta →</button></div></form></div><?php endif;?></section>
<aside class="quiz-sidebar"><div class="session-stats"><span class="eyebrow">Nesta partida</span><strong><?=$_SESSION['quiz_acertos']?><small> / <?=$total?></small></strong><p>respostas corretas até agora</p><div class="session-rewards"><span>◈ <?=20+$_SESSION['quiz_acertos']*10?> moedas base</span><span>✧ <?=$_SESSION['quiz_acertos']*10?> XP base</span></div><small>Recebidos ao concluir. Bônus são somados no resultado.</small></div><div class="session-powers"><h3>Suas habilidades</h3><?php require __DIR__.'/powers.php';?><?php if($bonuses['hint']):?><?php if(!$_SESSION['quiz_dica_usada']&&!$feedback):?><form method="post"><input type="hidden" name="nonce" value="<?=$_SESSION['quiz_nonce']?>"><input type="hidden" name="pos" value="<?=$pos?>"><button class="btn-secundario" name="acao" value="dica">✦ Usar dica · 1 disponível</button></form><?php else:?><p class="dica"><?=$_SESSION['quiz_dica_usada']?'✓ Dica já utilizada nesta partida.':'A dica estará disponível na próxima questão.'?></p><?php endif;?><?php endif;?></div><div class="study-tip"><span>✧</span><p>Não precisa correr. Pense em como os nós se conectam e simule as operações antes de responder.</p></div><a class="text-link" href="quiz.php?preparar=1">Voltar à preparação</a></aside></div>
<?php endif;?></div><script src="assets/js/game.js"></script>
