<div class="container game-page" data-wardrobe>
<nav class="game-nav" aria-label="Área de jogos"><a href="area-usuario.php">← Minha área</a><div><a href="quiz.php">Quiz</a><a href="avatar.php" <?=$inventory?'aria-current="page"':''?>>Personagem</a><a href="loja.php" <?=!$inventory?'aria-current="page"':''?>>Loja</a></div><span class="coin-pill">◈ <?=number_format($u['moedas'],0,',','.')?> <span>moedas</span></span></nav>
<header class="game-heading"><div><span class="eyebrow"><?=$inventory?'Monte seu visual':'Recompense sua curiosidade'?></span><h1><?=$inventory?'Seu próximo nível tem estilo.':'Pequenos itens. Novas possibilidades.'?></h1><p><?=$inventory?'Personalize seu personagem e prepare suas habilidades para o próximo desafio.':'Experimente acessórios, descubra habilidades e transforme suas moedas em conquistas.'?></p></div></header>
<?php mostrarFlash();?>
<div class="wardrobe-layout">
<aside class="character-panel">
<div class="stage-top"><span class="badge">Nível <?=(int)$u['nivel']?></span><span class="live-label" data-preview-status>Visual equipado</span></div>
<div class="character-scene"><?php require __DIR__.'/character.php';?><span class="scene-spark spark-one">✦</span><span class="scene-spark spark-two">+</span><span class="scene-spark spark-three">✧</span></div>
<div class="character-caption"><h2><?=htmlspecialchars($u['nome'])?></h2><p>Explorador de estruturas</p><button type="button" class="preview-reset" data-reset-preview hidden>↶ Voltar ao visual equipado</button></div>
<div class="level-track"><div><span><?=(int)$u['xp']?> XP</span><span><?=100-($u['xp']%100)?> para o próximo nível</span></div><progress max="100" value="<?=$u['xp']%100?>" aria-label="Progresso para o próximo nível"></progress></div>
<div class="loadout"><h3>Seu equipamento</h3><?php foreach(Game::CATEGORIES as $category=>$label):$equipped=$gear[$category];?><div class="loadout-slot"><span class="slot-icon"><?=htmlspecialchars($equipped['icone']??['chapeu'=>'◇','rosto'=>'☺','roupa'=>'♧'][$category])?></span><div><small><?=$label?></small><strong><?=htmlspecialchars($equipped['nome']??'Visual básico')?></strong></div><?php if($equipped):?><form method="post"><?=campoCsrf()?><button class="remove-gear" name="desequipar" value="<?=$category?>" aria-label="Remover <?=htmlspecialchars($equipped['nome'])?>">×</button></form><?php endif;?></div><?php endforeach;?></div>
<div class="power-summary"><h3>Habilidades equipadas</h3><?php if(array_filter($abilities)):?><ul><?php foreach($abilities as $ability):if(!$ability)continue;?><li>✦ <?=htmlspecialchars($ability)?></li><?php endforeach;?></ul><?php else:?><p>Equipe acessórios para ganhar bônus e desbloquear uma dica.</p><?php endif;?><small>Ativadas ao iniciar um novo quiz.</small></div>
<a class="btn-primario stage-cta" href="quiz.php">Ir para o quiz →</a>
</aside>
<section class="catalog-panel" aria-label="<?=$inventory?'Inventário':'Catálogo da loja'?>">
<div class="catalog-heading"><div><h2><?=$inventory?'Seu guarda-roupa':'Explore a coleção'?></h2><p><?=count($owned)?> de <?=count($items)?> itens desbloqueados</p></div><a href="<?=$inventory?'loja.php':'avatar.php'?>"><?=$inventory?'Visitar a loja ↗':'Meu inventário ↗'?></a></div>
<div class="catalog-tools"><div class="category-tabs" role="group" aria-label="Filtrar categoria"><button type="button" data-filter="all" aria-pressed="true">Todos</button><?php foreach(Game::CATEGORIES as $category=>$label):?><button type="button" data-filter="<?=$category?>" aria-pressed="false"><?=$label?></button><?php endforeach;?></div>
<div class="catalog-options"><label class="search-box"><span aria-hidden="true">⌕</span><input type="search" data-item-search placeholder="Buscar um item…" aria-label="Buscar item"></label><label class="filter-check"><input type="checkbox" data-owned-filter <?=$inventory?'checked':''?>> Só meus itens</label><?php if(!$inventory):?><label class="filter-check"><input type="checkbox" data-affordable-filter> Posso comprar</label><?php endif;?></div></div>
<p class="catalog-count" data-filter-count role="status"><?=count($items)?> itens na coleção</p>
<div class="collection-grid">
<?php foreach($items as $i):$isOwned=in_array((int)$i['id'],$owned,true);$equipped=(int)($u[Game::FIELDS[$i['categoria']]??'']??0)===(int)$i['id'];$missing=max(0,$i['preco']-$u['moedas']);$variant=Game::variant($i);?>
<article class="collection-card <?=$equipped?'is-equipped':''?>" data-item data-category="<?=htmlspecialchars($i['categoria'])?>" data-owned="<?=$isOwned?'true':'false'?>" data-affordable="<?=$missing===0?'true':'false'?>" data-name="<?=htmlspecialchars($i['nome'])?>">
<div class="item-art art-<?=$variant?>"><span class="item-category"><?=Game::CATEGORIES[$i['categoria']]??'Especial'?></span><?php if($equipped):?><span class="item-status">✓ Equipado</span><?php elseif($isOwned):?><span class="item-status owned-status">✓ Seu item</span><?php endif;?><span class="item-emoji" aria-hidden="true"><?=htmlspecialchars($i['icone'])?></span><button type="button" class="try-item" data-preview-category="<?=htmlspecialchars($i['categoria'])?>" data-preview-variant="<?=$variant?>" data-preview-name="<?=htmlspecialchars($i['nome'])?>" aria-label="Experimentar <?=htmlspecialchars($i['nome'])?>">Experimentar ↗</button></div>
<div class="item-info"><h3><?=htmlspecialchars($i['nome'])?></h3><p><?=htmlspecialchars($i['descricao'])?></p><div class="item-power"><span aria-hidden="true">✦</span><span><?=htmlspecialchars($i['habilidade']?:'Um novo sorriso. Item estético gratuito.')?></span></div>
<div class="item-purchase"><strong><?=$i['preco']>0?'◈ '.(int)$i['preco']:'Grátis'?></strong><?php if($equipped):?><span class="equipped-label">Em uso</span><?php else:?><form method="post"><?=campoCsrf()?><?php if($isOwned):?><button name="equip" value="<?=$i['id']?>" class="btn-secundario">Equipar</button><?php else:?><button name="comprar" value="<?=$i['id']?>" class="btn-primario" <?=$missing?'disabled':''?>><?=$i['preco']==0?'Resgatar':($missing?'Bloqueado':'Comprar')?></button><?php endif;?></form><?php endif;?></div><?php if(!$isOwned&&$missing):?><p class="missing-coins">Faltam <?=$missing?> moedas · <a href="quiz.php">Ganhar no quiz</a></p><?php endif;?></div>
</article><?php endforeach;?></div>
<div class="catalog-empty" data-catalog-empty hidden><span>◇</span><h3>Nenhum item por aqui, ainda.</h3><p>Altere os filtros ou visite a loja para começar sua coleção.</p><button type="button" class="btn-secundario" data-clear-filters>Mostrar toda a coleção</button></div>
<div class="collection-note"><span>✦</span><p><strong>Um visual, três escolhas.</strong> Você pode equipar um chapéu, um rosto e uma roupa. Experimente à vontade; a prévia não compra nem equipa o item.</p></div>
</section></div></div><script src="assets/js/game.js"></script>
